/**
 * developer/tools.ts — Register the 11 developer-plugin MCP tools.
 *
 * Called by ILorePlugin.registerTools(server, ctx) only when the
 * developer plugin is active in the workspace. The tools reach the
 * graph through DeveloperApi; core server has no knowledge of them.
 *
 * Tools:
 *   code_query, code_context, link_knowledge_to_code
 *   code_flow_search, code_full_context, code_impact, code_cypher
 *     + gitnexus_* aliases (deprecated, kept for CLAUDE.md back-compat)
 *   list_repos, detect_changes, rename, who_is_working
 *
 * Naming note: the four tools that delegate to the underlying code
 * indexer (formerly gitnexus_*) are exposed under the `code_*` family
 * to keep the user-facing surface free of internal-dependency names.
 * The indexer dependency is plumbing; users see "Lore code intelligence."
 *
 * Back-compat aliases: the auto-generated CLAUDE.md / AGENTS.md gitnexus
 * blocks (regenerated by the code-indexer post-commit hook) still teach
 * agents the old gitnexus_* names. Until the generator template is
 * patched, the aliases below keep both names live so docs and tools
 * stay in sync.
 */

import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { PluginContext } from '@lore-core/plugins/types.js';
import type { DeveloperApi } from './api.js';
import { proxyQuery, proxyContext, proxyImpact, proxyCypher } from './gitnexusProxy.js';
import { detectChanges, rename, listRepos, formatReposMarkdown } from './nativeTools.js';

interface WalLike {
    append(op: string, data: unknown): void;
}

interface SyncStatusLike {
    walPending: number;
    lastSync: string;
    hasAdapter: boolean;
    isAutoSyncing: boolean;
}

interface SyncEngineLike {
    getWal(): WalLike;
    getStatus?(): SyncStatusLike;
}

export function registerDeveloperTools(
    server: McpServer,
    api: DeveloperApi,
    ctx: PluginContext,
): void {
    // WAL access via ctx.syncEngine — the WAL is core infrastructure
    // (offline-first sync lives in the core engine); plugins write to
    // it via this narrow cast rather than importing the engine directly.
    const syncEngine = ctx.syncEngine as SyncEngineLike | null;
    const wal = syncEngine?.getWal?.();

    /* ─── code_query ───────────────────────────────────────────── */
    server.tool(
        'code_query',
        'Search code symbols by name or file path. Returns functions, classes, methods, and interfaces from the unified graph.',
        {
            query: z.string().describe('Search term — matched against symbol name and file path'),
            repo: z.string().optional().describe('Optional: filter by repository name'),
            limit: z.number().optional().describe('Maximum results (default: 20)'),
        },
        async ({ query, repo, limit }) => {
            try {
                const results = await api.queryCodeSymbols(query, repo, limit ?? 20);
                if (results.length === 0) {
                    return {
                        content: [{ type: 'text' as const, text: `No code symbols found matching "${query}". Run "lore index" to import code.` }],
                    };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            count: results.length,
                            symbols: results.map((s) => ({ uid: s.uid, name: s.name, kind: s.kind, filePath: s.filePath, line: `${s.startLine}-${s.endLine}`, repo: s.repo })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── code_context ─────────────────────────────────────────── */
    server.tool(
        'code_context',
        '360° view of a code symbol — shows callers, callees, and connected knowledge nodes (decisions, conventions, bugs)',
        { uid: z.string().describe('CodeSymbol UID from a prior code_query result') },
        async ({ uid }) => {
            try {
                const context = await api.getCodeSymbolContext(uid);
                if (!context.symbol) {
                    return { content: [{ type: 'text' as const, text: `No code symbol found with UID "${uid}".` }] };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            symbol: {
                                uid: context.symbol.uid,
                                name: context.symbol.name,
                                kind: context.symbol.kind,
                                filePath: context.symbol.filePath,
                                line: `${context.symbol.startLine}-${context.symbol.endLine}`,
                                repo: context.symbol.repo,
                            },
                            callers: context.callers.map((s) => ({ name: s.name, kind: s.kind, filePath: s.filePath })),
                            callees: context.callees.map((s) => ({ name: s.name, kind: s.kind, filePath: s.filePath })),
                            knowledge: context.knowledge.map((k) => ({ id: k.id, type: k.type, label: k.label })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── link_knowledge_to_code ───────────────────────────────── */
    server.tool(
        'link_knowledge_to_code',
        'Create a cross-pillar edge linking a knowledge node (decision, convention, bug) to a code symbol. Enables queries like "what decisions affect this function?"',
        {
            nodeId: z.string().describe('LoreNode ID'),
            symbolUid: z.string().describe('CodeSymbol UID from a prior code_query result'),
            relation: z.string().optional().describe('Relationship type (default: "applies_to")'),
        },
        async ({ nodeId, symbolUid, relation }) => {
            try {
                const resolved = relation ?? 'applies_to';
                await api.linkKnowledgeToCode(nodeId, symbolUid, resolved);
                wal?.append('link_knowledge_to_code', { nodeId, symbolUid, relation: resolved });
                return { content: [{ type: 'text' as const, text: `Linked knowledge "${nodeId}" → code "${symbolUid}" (${resolved})` }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── code intelligence (live indexer) ─────────────────────── */
    server.tool(
        'code_flow_search',
        'Search code execution flows by concept. Returns process-grouped results ranked by relevance (BM25 + semantic vector search).',
        {
            query: z.string().describe('Natural language or keyword search query'),
            repo: z.string().optional().describe('Target repository name'),
            goal: z.string().optional().describe('What you want to find — helps ranking'),
        },
        async ({ query, repo, goal }) => {
            const result = proxyQuery(query, repo, goal);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    server.tool(
        'code_full_context',
        '360° live-indexer view of a code symbol: callers, callees, processes, imports. Deeper than code_context (which reads stored Lore data).',
        {
            name: z.string().describe('Symbol name'),
            repo: z.string().optional().describe('Target repository name'),
        },
        async ({ name, repo }) => {
            const result = proxyContext(name, repo);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    server.tool(
        'code_impact',
        'Blast radius analysis: what breaks if you change a symbol. Returns direct callers, indirect dependencies, and risk level.',
        {
            target: z.string().describe('Symbol or file to analyze'),
            repo: z.string().optional().describe('Target repository name'),
            direction: z.string().optional().describe('"upstream" (what depends on this) or "downstream"'),
        },
        async ({ target, repo, direction }) => {
            const result = proxyImpact(target, repo, direction);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    server.tool(
        'code_cypher',
        'Execute a raw Cypher query against the code knowledge graph (advanced — prefer code_query / code_flow_search for normal use).',
        {
            query: z.string().describe('Cypher query to execute'),
            repo: z.string().optional().describe('Target repository name'),
        },
        async ({ query, repo }) => {
            const result = proxyCypher(query, repo);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    /* ─── back-compat aliases ──────────────────────────────────── */
    //
    // The four tools above were renamed from gitnexus_* to code_* on
    // 2026-04-26. The auto-generated CLAUDE.md / AGENTS.md sections
    // (rewritten by the underlying code-indexer's post-commit hook)
    // still teach agents to call the old gitnexus_* names. Until the
    // generator template is patched (parked follow-up), these aliases
    // keep the old names working so agents reading CLAUDE.md don't
    // hit "tool not found." Aliases intentionally carry a deprecation
    // hint in the description so the LLM picks the new name when
    // given a choice in the tool list.

    server.tool(
        'gitnexus_query',
        'Deprecated alias for code_flow_search — kept for back-compat with auto-generated CLAUDE.md docs. Prefer code_flow_search going forward.',
        {
            query: z.string().describe('Natural language or keyword search query'),
            repo: z.string().optional().describe('Target repository name'),
            goal: z.string().optional().describe('What you want to find — helps ranking'),
        },
        async ({ query, repo, goal }) => {
            const result = proxyQuery(query, repo, goal);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    server.tool(
        'gitnexus_context',
        'Deprecated alias for code_full_context — kept for back-compat with auto-generated CLAUDE.md docs. Prefer code_full_context going forward.',
        {
            name: z.string().describe('Symbol name'),
            repo: z.string().optional().describe('Target repository name'),
        },
        async ({ name, repo }) => {
            const result = proxyContext(name, repo);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    server.tool(
        'gitnexus_impact',
        'Deprecated alias for code_impact — kept for back-compat with auto-generated CLAUDE.md docs. Prefer code_impact going forward.',
        {
            target: z.string().describe('Symbol or file to analyze'),
            repo: z.string().optional().describe('Target repository name'),
            direction: z.string().optional().describe('"upstream" (what depends on this) or "downstream"'),
        },
        async ({ target, repo, direction }) => {
            const result = proxyImpact(target, repo, direction);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    server.tool(
        'gitnexus_cypher',
        'Deprecated alias for code_cypher — kept for back-compat with auto-generated CLAUDE.md docs. Prefer code_cypher going forward.',
        {
            query: z.string().describe('Cypher query to execute'),
            repo: z.string().optional().describe('Target repository name'),
        },
        async ({ query, repo }) => {
            const result = proxyCypher(query, repo);
            return { content: [{ type: 'text' as const, text: result.text }], isError: !result.success };
        },
    );

    /* ─── code_similar (Phase 2) ───────────────────────────────── */
    server.tool(
        'code_similar',
        'Find existing code symbols semantically similar to a proposed snippet. Use BEFORE writing new functions/classes to avoid duplicating something that already exists. Returns top matches with similarity scores and recommended action.',
        {
            content: z.string().describe('The proposed code snippet (function body, class declaration, etc.) you are about to write'),
            language: z.string().optional().describe('Optional language hint (e.g. "typescript", "python") — used as embedding context'),
            repo: z.string().optional().describe('Optional: restrict search to a single repository'),
            k: z.number().optional().describe('Max matches to return (default: 5)'),
            warn_threshold: z.number().optional().describe('Cosine similarity threshold above which a "warn" decision fires (default: 0.78). Higher = stricter; lower = more warnings.'),
        },
        async ({ content, language, repo, k, warn_threshold }) => {
            try {
                const decision = await api.evaluatePreWrite(content, {
                    language,
                    repo,
                    k: k ?? 5,
                    warnThreshold: warn_threshold,
                });
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            decision: decision.decision,
                            recommendation: decision.recommendation,
                            strong_match: decision.strongMatch,
                            top_match: decision.topMatch,
                            matches: decision.matches.map((m) => ({
                                name: m.name,
                                kind: m.kind,
                                file: `${m.filePath}${m.startLine ? ':' + m.startLine : ''}`,
                                repo: m.repo,
                                similarity: Number(m.score.toFixed(3)),
                                lore_node_id: m.loreNodeId,
                            })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── list_repos ───────────────────────────────────────────── */
    server.tool(
        'list_repos',
        'List all repositories indexed by Lore',
        {},
        async () => {
            try {
                const repos = listRepos();
                return { content: [{ type: 'text' as const, text: formatReposMarkdown(repos) }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Failed to list repos: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── detect_changes ───────────────────────────────────────── */
    server.tool(
        'detect_changes',
        'Analyze uncommitted git changes and find affected code symbols in the knowledge graph',
        {
            repo_path: z.string().optional().describe('Path to git repository (default: cwd)'),
            scope: z.enum(['unstaged', 'staged', 'all']).optional().describe('Which changes to detect (default: unstaged)'),
        },
        async ({ repo_path, scope }) => {
            try {
                const repoPath = repo_path ?? process.cwd();
                const result = await detectChanges(api, repoPath, scope ?? 'unstaged');
                const lines: string[] = [`## Uncommitted Changes (${result.totalFilesChanged} files)`, ''];
                if (result.changedSymbols.length > 0) {
                    lines.push(`### Affected Symbols (${result.changedSymbols.length})`, '');
                    lines.push('| Symbol | Kind | File | Change |', '|---|---|---|---|');
                    for (const s of result.changedSymbols) {
                        lines.push(`| ${s.name} | ${s.kind} | ${s.filePath} | ${s.changeType} |`);
                    }
                }
                if (result.unmappedFiles.length > 0) {
                    lines.push('', `### Unmapped Files (${result.unmappedFiles.length})`, '');
                    for (const f of result.unmappedFiles) lines.push(`- ${f}`);
                }
                if (result.totalFilesChanged === 0) lines.push('No uncommitted changes detected.');
                return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Failed: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── rename ───────────────────────────────────────────────── */
    server.tool(
        'rename',
        'Multi-file coordinated rename using knowledge graph + text search. Preview by default (dry_run=true).',
        {
            symbol_name: z.string().describe('Current symbol name to rename'),
            new_name: z.string().describe('The new name for the symbol'),
            repo_path: z.string().optional().describe('Path to repository root'),
            dry_run: z.boolean().optional().describe('Preview without applying (default: true)'),
        },
        async ({ symbol_name, new_name, repo_path, dry_run }) => {
            try {
                const repoPath = repo_path ?? process.cwd();
                const isDryRun = dry_run ?? true;
                const result = await rename(api, symbol_name, new_name, repoPath, isDryRun);
                const lines: string[] = [
                    `## Rename: ${symbol_name} → ${new_name}`,
                    `**Mode:** ${isDryRun ? 'Preview (dry run)' : 'Applied'}`,
                    `**Files affected:** ${result.filesAffected}`,
                    `**Total edits:** ${result.edits.length}`,
                    '',
                ];
                if (result.edits.length > 0) {
                    lines.push('| File | Line | Confidence |', '|---|---|---|');
                    for (const edit of result.edits) {
                        const relPath = edit.filePath.replace(repoPath + '/', '');
                        lines.push(`| ${relPath} | L${edit.line} | ${edit.source} |`);
                    }
                } else {
                    lines.push('No references found for this symbol.');
                }
                return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Rename failed: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── who_is_working ───────────────────────────────────────────
     * Moved from core server.ts in Q1.2. Team-activity awareness is
     * a developer-plugin concept (filters by `symbol`, surfaces dev
     * activity) and belongs here; core no longer imports it.
     * Reads sync status via the same ctx.syncEngine narrow cast used
     * for WAL access above.
     */
    server.tool(
        'who_is_working',
        'See team developer activity — who is working on what, filtered by symbol or file',
        {
            symbol: z.string().optional().describe('Filter by symbol name (e.g., "UserService")'),
        },
        async ({ symbol }) => {
            try {
                const status = syncEngine?.getStatus?.();
                if (!status || !status.hasAdapter) {
                    return {
                        content: [{
                            type: 'text' as const,
                            text: JSON.stringify({
                                message: 'No remote sync adapter configured — team awareness requires a shared backend (Groundfloor Dataplane).',
                                hint: 'Configure DATAPLANE_URL, DATAPLANE_API_KEY, DATAPLANE_TENANT_ID environment variables to enable team sync.',
                                localStatus: status
                                    ? { walPending: status.walPending, lastSync: status.lastSync }
                                    : { walPending: 0, lastSync: 'unknown' },
                            }, null, 2),
                        }],
                    };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            message: 'Team awareness is available.',
                            filter: symbol ?? 'all',
                            note: 'Query remote backend for active developers.',
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return {
                    content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
                    isError: true,
                };
            }
        },
    );
}
