/**
 * developer/tools.ts — Register the 11 developer-plugin MCP tools.
 *
 * Called by ILorePlugin.registerTools(server, ctx) only when the
 * developer plugin is active in the workspace. The tools reach the
 * graph through DeveloperApi; core server has no knowledge of them.
 *
 * Tools:
 *   code_query, code_context, link_knowledge_to_code
 *   code_flow_search, code_full_context, code_impact, code_cypher
 *     + gitnexus_* aliases (deprecated, kept for CLAUDE.md back-compat)
 *   list_repos, detect_changes, rename, who_is_working
 *
 * Naming note: the four tools that delegate to the underlying code
 * indexer (formerly gitnexus_*) are exposed under the `code_*` family
 * to keep the user-facing surface free of internal-dependency names.
 * The indexer dependency is plumbing; users see "Lore code intelligence."
 *
 * Back-compat aliases: the auto-generated CLAUDE.md / AGENTS.md gitnexus
 * blocks (regenerated by the code-indexer post-commit hook) still teach
 * agents the old gitnexus_* names. Until the generator template is
 * patched, the aliases below keep both names live so docs and tools
 * stay in sync.
 */

import { z } from 'zod';
import type { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import type { PluginContext } from '@lore-core/plugins/types.js';
import type { DeveloperApi } from './api.js';
import { findWriteKeyword } from './api.js';
import { detectChanges, rename, listRepos, formatReposMarkdown } from './nativeTools.js';

interface WalLike {
    append(op: string, data: unknown): void;
}

interface SyncStatusLike {
    walPending: number;
    lastSync: string;
    hasAdapter: boolean;
    isAutoSyncing: boolean;
}

interface SyncEngineLike {
    getWal(): WalLike;
    getStatus?(): SyncStatusLike;
}

export function registerDeveloperTools(
    server: McpServer,
    api: DeveloperApi,
    ctx: PluginContext,
): void {
    // WAL access via ctx.syncEngine — the WAL is core infrastructure
    // (offline-first sync lives in the core engine); plugins write to
    // it via this narrow cast rather than importing the engine directly.
    const syncEngine = ctx.syncEngine as SyncEngineLike | null;
    const wal = syncEngine?.getWal?.();

    /* ─── code_query ───────────────────────────────────────────── */
    server.tool(
        'code_query',
        'Search code symbols by name or file path. Returns functions, classes, methods, and interfaces from the unified graph. AUTHORITATIVE — this is the indexed graph, every relevant symbol matching the query is in the result. Use this INSTEAD OF Grep / Bash find for code-symbol questions; the result is current and complete.',
        {
            query: z.string().describe('Search term — matched against symbol name and file path'),
            repo: z.string().optional().describe('Optional: filter by repository name'),
            limit: z.number().optional().describe('Maximum results (default: 20)'),
        },
        async ({ query, repo, limit }) => {
            try {
                const results = await api.queryCodeSymbols(query, repo, limit ?? 20);
                if (results.length === 0) {
                    return {
                        content: [{ type: 'text' as const, text: `No code symbols found matching "${query}". Run "lore index" to import code.` }],
                    };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            count: results.length,
                            symbols: results.map((s) => ({ uid: s.uid, name: s.name, kind: s.kind, filePath: s.filePath, line: `${s.startLine}-${s.endLine}`, repo: s.repo })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── code_context ─────────────────────────────────────────── */
    server.tool(
        'code_context',
        '360° view of a code symbol — shows callers, callees, and connected knowledge nodes (decisions, conventions, bugs). AUTHORITATIVE — answers "who calls this / what does it call / what knowledge attaches to it" in one call. Use this INSTEAD OF reading the file + grep-ing for callers; the data is from the indexed graph and is current.',
        { uid: z.string().describe('CodeSymbol UID from a prior code_query result') },
        async ({ uid }) => {
            try {
                const context = await api.getCodeSymbolContext(uid);
                if (!context.symbol) {
                    return { content: [{ type: 'text' as const, text: `No code symbol found with UID "${uid}".` }] };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            symbol: {
                                uid: context.symbol.uid,
                                name: context.symbol.name,
                                kind: context.symbol.kind,
                                filePath: context.symbol.filePath,
                                line: `${context.symbol.startLine}-${context.symbol.endLine}`,
                                repo: context.symbol.repo,
                            },
                            callers: context.callers.map((s) => ({ name: s.name, kind: s.kind, filePath: s.filePath })),
                            callees: context.callees.map((s) => ({ name: s.name, kind: s.kind, filePath: s.filePath })),
                            knowledge: context.knowledge.map((k) => ({ id: k.id, type: k.type, label: k.label })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── link_knowledge_to_code ───────────────────────────────── */
    server.tool(
        'link_knowledge_to_code',
        'Create a cross-pillar edge linking a knowledge node (decision, convention, bug) to a code symbol. Enables queries like "what decisions affect this function?"',
        {
            nodeId: z.string().describe('LoreNode ID'),
            symbolUid: z.string().describe('CodeSymbol UID from a prior code_query result'),
            relation: z.string().optional().describe('Relationship type (default: "applies_to")'),
        },
        async ({ nodeId, symbolUid, relation }) => {
            try {
                const resolved = relation ?? 'applies_to';
                await api.linkKnowledgeToCode(nodeId, symbolUid, resolved);
                wal?.append('link_knowledge_to_code', { nodeId, symbolUid, relation: resolved });
                return { content: [{ type: 'text' as const, text: `Linked knowledge "${nodeId}" → code "${symbolUid}" (${resolved})` }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── code intelligence (Kùzu-backed; was gitnexus-CLI proxy) ───── */
    //
    // 2026-04-30: code_flow_search / code_full_context / code_impact
    // were proxies to the gitnexus CLI (subprocess + temp file + JSON
    // parse). With Phase 7 cutover prep landed, these now read directly
    // from the developer plugin's Kùzu graph via api.queryCodeSymbols /
    // api.getCodeSymbolContext / api.computeCodeBlastRadius. Sub-second
    // in-process replaces ~50–500ms subprocess. Same tool names, same
    // shapes (back-compat), but the index they read is the same one
    // every other Lore tool reads — single source of truth.
    server.tool(
        'code_flow_search',
        'Search code symbols by name or file path. Reads from the unified developer-plugin Kùzu graph (same index as code_query / code_context).',
        {
            query: z.string().describe('Search term — matched against symbol name and file path'),
            repo: z.string().optional().describe('Target repository name'),
            limit: z.number().optional().describe('Maximum results (default: 20)'),
        },
        async ({ query, repo, limit }) => {
            try {
                const results = await api.queryCodeSymbols(query, repo, limit ?? 20);
                if (results.length === 0) {
                    return {
                        content: [{ type: 'text' as const, text: `No code symbols found matching "${query}". Run "lore index" to import code.` }],
                    };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            count: results.length,
                            symbols: results.map((s) => ({
                                uid: s.uid,
                                name: s.name,
                                kind: s.kind,
                                filePath: s.filePath,
                                line: `${s.startLine}-${s.endLine}`,
                                repo: s.repo,
                            })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    server.tool(
        'code_full_context',
        '360° view of a code symbol — symbol metadata, callers, callees, linked knowledge nodes, AND THE SOURCE SLICE between the symbol\'s startLine and endLine. AUTHORITATIVE — the source slice IS the implementation; you do NOT need to Read the file separately. Pass include_source: false to skip the slice on long symbols if you only want metadata.',
        {
            name: z.string().describe('Symbol name or qualified name'),
            repo: z.string().optional().describe('Optional repository filter applied during the name lookup'),
            include_source: z.boolean().optional().describe('Include the source-code slice (default: true). Set false to get metadata only.'),
            max_source_chars: z.number().optional().describe('Maximum characters of source to return (default: 4000). Slice is truncated with a ─SNIP─ marker if longer.'),
        },
        async ({ name, repo, include_source, max_source_chars }) => {
            try {
                // Look up the uid by name first, then expand context.
                const matches = await api.queryCodeSymbolsByName(name);
                const filtered = repo ? matches.filter((m) => m.repo === repo) : matches;
                if (filtered.length === 0) {
                    return {
                        content: [{ type: 'text' as const, text: `Symbol "${name}"${repo ? ` in repo "${repo}"` : ''} not found.` }],
                    };
                }
                const target = filtered[0];
                const ctx = await api.getCodeSymbolContext(target.uid);

                // Read the source slice — this is the eval-headline fix
                // (commits 9c287c6 → 0e25f61 showed the agent reading the
                // file after every code_full_context call, doubling cost).
                // Returning the slice inline eliminates the follow-up Read.
                const wantSource = include_source !== false;
                const maxChars = Math.max(200, Math.min(20000, max_source_chars ?? 4000));
                let sourceSlice: string | null = null;
                let sourceTruncated = false;
                let sourceError: string | null = null;
                if (wantSource && target.filePath && target.startLine && target.endLine) {
                    try {
                        // Resolve the abs path: registry knows repo→absPath
                        const repoEntry = api.getGitNexusRepo(target.repo);
                        const absDir = repoEntry?.path;
                        if (!absDir) {
                            sourceError = `repo "${target.repo}" not in registry; cannot resolve abs path`;
                        } else {
                            const fs = await import('node:fs/promises');
                            const path = await import('node:path');
                            const absFile = path.join(absDir, target.filePath);
                            const all = await fs.readFile(absFile, 'utf-8');
                            const lines = all.split('\n');
                            const start = Math.max(0, target.startLine - 1);
                            const end = Math.min(lines.length, target.endLine);
                            let slice = lines.slice(start, end).join('\n');
                            if (slice.length > maxChars) {
                                slice = slice.slice(0, maxChars) + '\n─SNIP─ (truncated; pass max_source_chars to extend)';
                                sourceTruncated = true;
                            }
                            sourceSlice = slice;
                        }
                    } catch (err) {
                        sourceError = (err as Error).message;
                    }
                }

                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            symbol: ctx.symbol,
                            ambiguous: filtered.length > 1
                                ? { totalMatches: filtered.length, otherMatches: filtered.slice(1).map((m) => ({ uid: m.uid, file: m.filePath, repo: m.repo })) }
                                : undefined,
                            callers: ctx.callers.map((c) => ({ uid: c.uid, name: c.name, kind: c.kind, file: c.filePath })),
                            callees: ctx.callees.map((c) => ({ uid: c.uid, name: c.name, kind: c.kind, file: c.filePath })),
                            knowledge: ctx.knowledge,
                            source: sourceSlice,
                            sourceTruncated,
                            sourceError,
                            sourceLineRange: target.startLine && target.endLine ? `${target.startLine}-${target.endLine}` : null,
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    server.tool(
        'code_impact',
        'Blast radius analysis: depth-tiered (d1/d2/d3) reachability over CodeRelation edges. d1 = WILL BREAK; d2 = LIKELY AFFECTED; d3 = MAY NEED TESTING.',
        {
            target: z.string().describe('Symbol uid or name'),
            direction: z.string().optional().describe('"upstream" (what depends on this) or "downstream" (what this depends on). Default: upstream.'),
            max_depth: z.number().optional().describe('Maximum BFS depth (default: 3, max: 5)'),
        },
        async ({ target, direction, max_depth }) => {
            try {
                const dir: 'upstream' | 'downstream' = direction === 'downstream' ? 'downstream' : 'upstream';
                const depth = Math.max(1, Math.min(5, max_depth ?? 3));
                const result = await api.computeCodeBlastRadius(target, dir, depth);
                if (result.symbol === null) {
                    return {
                        content: [{ type: 'text' as const, text: `Symbol "${target}" not found.` }],
                    };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            symbol: { uid: result.symbol.uid, name: result.symbol.name, file: result.symbol.filePath },
                            direction: dir,
                            d1: result.d1.map((s) => ({ uid: s.uid, name: s.name, file: s.filePath })),
                            d2: result.d2.map((s) => ({ uid: s.uid, name: s.name, file: s.filePath })),
                            d3: result.d3.map((s) => ({ uid: s.uid, name: s.name, file: s.filePath })),
                            riskLevel: result.d1.length > 5 ? 'CRITICAL' : result.d1.length > 0 ? 'HIGH' : 'LOW',
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    server.tool(
        'code_cypher',
        'Execute a read-only Cypher query against the developer-plugin Kùzu graph (advanced — prefer code_query / code_flow_search for normal use). Mutation keywords (CREATE/DELETE/DROP/MERGE/SET/DETACH/COPY/INSTALL/LOAD) are rejected.',
        {
            query: z.string().describe('Cypher query to execute (read-only)'),
            parameters: z.record(z.string(), z.unknown()).optional().describe('Optional parameter map'),
            max_rows: z.number().optional().describe('Maximum rows returned (default: 1000)'),
        },
        async ({ query, parameters, max_rows }) => {
            const writeKw = findWriteKeyword(query);
            if (writeKw) {
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            error: 'read-only',
                            rejectedKeyword: writeKw,
                            note: `code_cypher is read-only. Mutation keyword "${writeKw}" detected. Use the developer plugin's typed APIs (or atlas-cutover-execute.mjs for Phase 7) for graph mutations.`,
                        }, null, 2),
                    }],
                    isError: true,
                };
            }
            try {
                const result = await api.executeRawCypher(query, parameters, { maxRows: max_rows ?? 1000 });
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            count: result.rows.length,
                            truncated: result.truncated,
                            rows: result.rows,
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return {
                    content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
                    isError: true,
                };
            }
        },
    );

    // gitnexus_* aliases dropped 2026-04-30. They survived through one
    // release after Phase 8 (the deprecation window we promised in
    // CHANGELOG). Agents that still call gitnexus_query / _context /
    // _impact / _cypher get a "tool not found" error and should switch
    // to the code_* names. CLAUDE.md / AGENTS.md regen now writes the
    // code_* names directly.

    /* ─── code_similar (Phase 2) ───────────────────────────────── */
    server.tool(
        'code_similar',
        'Find existing code symbols semantically similar to a proposed snippet. Use BEFORE writing new functions/classes to avoid duplicating something that already exists. Returns top matches with similarity scores and recommended action.',
        {
            content: z.string().describe('The proposed code snippet (function body, class declaration, etc.) you are about to write'),
            language: z.string().optional().describe('Optional language hint (e.g. "typescript", "python") — used as embedding context'),
            repo: z.string().optional().describe('Optional: restrict search to a single repository'),
            k: z.number().optional().describe('Max matches to return (default: 5)'),
            warn_threshold: z.number().optional().describe('Cosine similarity threshold above which a "warn" decision fires (default: 0.78). Higher = stricter; lower = more warnings.'),
        },
        async ({ content, language, repo, k, warn_threshold }) => {
            try {
                const decision = await api.evaluatePreWrite(content, {
                    language,
                    repo,
                    k: k ?? 5,
                    warnThreshold: warn_threshold,
                });
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            decision: decision.decision,
                            recommendation: decision.recommendation,
                            strong_match: decision.strongMatch,
                            top_match: decision.topMatch,
                            matches: decision.matches.map((m) => ({
                                name: m.name,
                                kind: m.kind,
                                file: `${m.filePath}${m.startLine ? ':' + m.startLine : ''}`,
                                repo: m.repo,
                                similarity: Number(m.score.toFixed(3)),
                                lore_node_id: m.loreNodeId,
                            })),
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── list_repos ───────────────────────────────────────────── */
    server.tool(
        'list_repos',
        'List all repositories indexed by Lore',
        {},
        async () => {
            try {
                const repos = listRepos();
                return { content: [{ type: 'text' as const, text: formatReposMarkdown(repos) }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Failed to list repos: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── detect_changes ───────────────────────────────────────── */
    server.tool(
        'detect_changes',
        'Analyze uncommitted git changes and find affected code symbols in the knowledge graph',
        {
            repo_path: z.string().optional().describe('Path to git repository (default: cwd)'),
            scope: z.enum(['unstaged', 'staged', 'all']).optional().describe('Which changes to detect (default: unstaged)'),
        },
        async ({ repo_path, scope }) => {
            try {
                const repoPath = repo_path ?? process.cwd();
                const result = await detectChanges(api, repoPath, scope ?? 'unstaged');
                const lines: string[] = [`## Uncommitted Changes (${result.totalFilesChanged} files)`, ''];
                if (result.changedSymbols.length > 0) {
                    lines.push(`### Affected Symbols (${result.changedSymbols.length})`, '');
                    lines.push('| Symbol | Kind | File | Change |', '|---|---|---|---|');
                    for (const s of result.changedSymbols) {
                        lines.push(`| ${s.name} | ${s.kind} | ${s.filePath} | ${s.changeType} |`);
                    }
                }
                if (result.unmappedFiles.length > 0) {
                    lines.push('', `### Unmapped Files (${result.unmappedFiles.length})`, '');
                    for (const f of result.unmappedFiles) lines.push(`- ${f}`);
                }
                if (result.totalFilesChanged === 0) lines.push('No uncommitted changes detected.');
                return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Failed: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── rename ───────────────────────────────────────────────── */
    server.tool(
        'rename',
        'Multi-file coordinated rename using knowledge graph + text search. Preview by default (dry_run=true).',
        {
            symbol_name: z.string().describe('Current symbol name to rename'),
            new_name: z.string().describe('The new name for the symbol'),
            repo_path: z.string().optional().describe('Path to repository root'),
            dry_run: z.boolean().optional().describe('Preview without applying (default: true)'),
        },
        async ({ symbol_name, new_name, repo_path, dry_run }) => {
            try {
                const repoPath = repo_path ?? process.cwd();
                const isDryRun = dry_run ?? true;
                const result = await rename(api, symbol_name, new_name, repoPath, isDryRun);
                const lines: string[] = [
                    `## Rename: ${symbol_name} → ${new_name}`,
                    `**Mode:** ${isDryRun ? 'Preview (dry run)' : 'Applied'}`,
                    `**Files affected:** ${result.filesAffected}`,
                    `**Total edits:** ${result.edits.length}`,
                    '',
                ];
                if (result.edits.length > 0) {
                    lines.push('| File | Line | Confidence |', '|---|---|---|');
                    for (const edit of result.edits) {
                        const relPath = edit.filePath.replace(repoPath + '/', '');
                        lines.push(`| ${relPath} | L${edit.line} | ${edit.source} |`);
                    }
                } else {
                    lines.push('No references found for this symbol.');
                }
                return { content: [{ type: 'text' as const, text: lines.join('\n') }] };
            } catch (err) {
                return { content: [{ type: 'text' as const, text: `Rename failed: ${(err as Error).message}` }], isError: true };
            }
        },
    );

    /* ─── who_is_working ───────────────────────────────────────────
     * Moved from core server.ts in Q1.2. Team-activity awareness is
     * a developer-plugin concept (filters by `symbol`, surfaces dev
     * activity) and belongs here; core no longer imports it.
     * Reads sync status via the same ctx.syncEngine narrow cast used
     * for WAL access above.
     */
    server.tool(
        'who_is_working',
        'See team developer activity — who is working on what, filtered by symbol or file',
        {
            symbol: z.string().optional().describe('Filter by symbol name (e.g., "UserService")'),
        },
        async ({ symbol }) => {
            try {
                const status = syncEngine?.getStatus?.();
                if (!status || !status.hasAdapter) {
                    return {
                        content: [{
                            type: 'text' as const,
                            text: JSON.stringify({
                                message: 'No remote sync adapter configured — team awareness requires a shared backend (Groundfloor Dataplane).',
                                hint: 'Configure DATAPLANE_URL, DATAPLANE_API_KEY, DATAPLANE_TENANT_ID environment variables to enable team sync.',
                                localStatus: status
                                    ? { walPending: status.walPending, lastSync: status.lastSync }
                                    : { walPending: 0, lastSync: 'unknown' },
                            }, null, 2),
                        }],
                    };
                }
                return {
                    content: [{
                        type: 'text' as const,
                        text: JSON.stringify({
                            message: 'Team awareness is available.',
                            filter: symbol ?? 'all',
                            note: 'Query remote backend for active developers.',
                        }, null, 2),
                    }],
                };
            } catch (err) {
                return {
                    content: [{ type: 'text' as const, text: `Error: ${(err as Error).message}` }],
                    isError: true,
                };
            }
        },
    );
}
