/**
 * htmlExport.ts — Static self-contained HTML graph export (Phase 6 / C8).
 *
 * What this is:
 *   Produces a single HTML file with the graph rendered by vis-network
 *   (loaded via CDN). The file opens in any browser, shows nodes +
 *   edges with the same type coloring as Sigma, offline after first
 *   load, no Lore daemon required.
 *
 * Why graphify's approach here:
 *   - A shareable snapshot is a different tool than a live dashboard.
 *     graphify solved this well with vis-network-via-CDN-in-static-HTML.
 *     Porting the pattern gives us "email this .html to a teammate"
 *     without bringing graphify's whole snapshot-first model.
 *
 * Confidence coloring:
 *   - Extracted edges: solid, full opacity
 *   - Inferred edges:  dashed, 40% opacity
 *   - Ambiguous:       dotted, orange
 * This mirrors what SigmaCanvas does in the live UI — consistent
 * visual grammar between live + exported.
 */

import type { LoreGraphHandle } from '../storage/loreStorageClient.js';

// This module only ever calls shared-handle methods, so it is written
// against the engine-agnostic handle type rather than a concrete backend class.
type LoreGraph = LoreGraphHandle;

export interface HtmlExportOptions {
    /** Filter to a single project; omit for all. */
    project?: string;
    /** Max nodes (visual clutter ceiling). Default 500. */
    maxNodes?: number;
    /** Custom page title. */
    title?: string;
    /** Embed a custom preamble the viewer sees above the graph. */
    description?: string;
    /**
     * Security checklist #12 — CSP nonce for the page's inline <style> and
     * inline <script> tags. GET /api/export/html (routes/static.ts) always
     * generates one (mcp/http/helpers.ts's generateCspNonce) and passes it
     * here, then repeats the same value in the response's
     * Content-Security-Policy header (buildHtmlExportCsp) so the browser's
     * script-src/style-src 'nonce-<value>' matches these tags instead of
     * requiring 'unsafe-inline'. Callers with no CSP to satisfy (the `lore
     * export html` CLI, which writes a plain file to disk with no HTTP
     * response at all) omit it — the tags are then un-nonced, exactly as
     * before this option existed.
     */
    cspNonce?: string;
}

export async function exportGraphAsHtml(
    graph: LoreGraph,
    opts: HtmlExportOptions = {},
): Promise<string> {
    const maxNodes = opts.maxNodes ?? 500;
    const title = opts.title ?? 'Lore — Graph Snapshot';
    const description = opts.description ?? 'Offline-viewable snapshot generated by `lore export html`.';

    const topology = await graph.getTopology(maxNodes);

    // Only include LoreEdges with confidence (core edges). Externally-
    // contributed edges without confidence ship through as neutral gray.
    const visNodes = topology.nodes.map((n) => ({
        id: n.id,
        label: n.label ?? n.id,
        group: n.type ?? 'default',
        title: `<b>${escapeHtml(n.label ?? n.id)}</b><br>type: ${escapeHtml(n.type ?? '?')}<br>id: <code>${escapeHtml(n.id)}</code>`,
    }));

    const visEdges = topology.edges.map((e: any, idx: number) => {
        const conf = (e.confidence ?? 'extracted') as string;
        const score = typeof e.confidenceScore === 'number' ? e.confidenceScore : 1.0;
        const dashes = conf === 'inferred' ? [5, 5]
                     : conf === 'ambiguous' ? [2, 3]
                     : false;
        const color = conf === 'inferred' ? { color: 'rgba(148,163,184,0.35)' }
                    : conf === 'ambiguous' ? { color: 'rgba(245,158,11,0.5)' }
                    : { color: 'rgba(148,163,184,0.85)' };
        return {
            id: idx,
            from: e.from,
            to: e.to,
            label: e.label ?? '',
            dashes,
            color,
            title: `${escapeHtml(e.label ?? '')}<br>confidence: ${conf} (${score.toFixed(3)})`,
        };
    });

    // Make the JSON safe for embedding inside a <script> block.
    // Replace every `<` with its Unicode escape so that `</script>`,
    // `<!--`, and `<script` cannot break out of the script context,
    // regardless of node/edge content. Round-trips cleanly: JS `JSON.parse`
    // reads `<` as `<`, so the data is lossless.
    const rawJson = JSON.stringify({ nodes: visNodes, edges: visEdges });
    const payload = rawJson.replace(/</g, '\\u003c');
    const exportedAt = new Date().toISOString();

    // Security checklist #12 — when the caller (routes/static.ts) supplies a
    // CSP nonce, stamp it onto the inline <style> block and the inline
    // <script> block (the one carrying DATA + the vis.Network wiring) so
    // the response's script-src/style-src 'nonce-<value>' CSP directive
    // (buildHtmlExportCsp) allows them without 'unsafe-inline'. The
    // separate `<script src="https://unpkg.com/...">` CDN loader does NOT
    // need the nonce — it's allow-listed by origin in that same CSP, on
    // top of the SRI hash already pinned on the tag itself.
    const nonceAttr = opts.cspNonce ? ` nonce="${opts.cspNonce}"` : '';

    return [
        '<!DOCTYPE html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8">',
        `<title>${escapeHtml(title)}</title>`,
        // re-audit 2026-06-25 (supply-chain) — pin the version + Subresource
        // Integrity so an exported snapshot loads a known-good vis-network build,
        // not whatever "latest" unpkg serves when the file is opened later.
        '<script src="https://unpkg.com/vis-network@9.1.9/standalone/umd/vis-network.min.js" integrity="sha384-yxKDWWf0wwdUj/gPeuL11czrnKFQROnLgY8ll7En9NYoXibgg3C6NK/UDHNtUgWJ" crossorigin="anonymous"></script>',
        `<style${nonceAttr}>`,
        '  body { font-family: -apple-system, system-ui, sans-serif; margin: 0; padding: 0; background: #0f172a; color: #e2e8f0; }',
        '  header { padding: 1rem 1.5rem; background: #1e293b; border-bottom: 1px solid #334155; }',
        '  header h1 { margin: 0 0 0.25rem; font-size: 1.1rem; }',
        '  header p { margin: 0; font-size: 0.85rem; color: #94a3b8; }',
        '  #graph { width: 100vw; height: calc(100vh - 80px); }',
        '  .legend { position: fixed; right: 1rem; bottom: 1rem; padding: 0.75rem 1rem; background: rgba(30,41,59,0.95); border: 1px solid #475569; border-radius: 6px; font-size: 0.75rem; }',
        '  .legend div { display: flex; align-items: center; gap: 0.5rem; margin: 0.15rem 0; }',
        '  .legend span { display: inline-block; width: 1.25rem; border-top: 2px solid; }',
        '  .legend .solid  { border-style: solid;  border-color: #94a3b8; }',
        '  .legend .dashed { border-style: dashed; border-color: #94a3b8; }',
        '  .legend .dotted { border-style: dotted; border-color: #f59e0b; }',
        '</style>',
        '</head>',
        '<body>',
        '<header>',
        `  <h1>${escapeHtml(title)}</h1>`,
        `  <p>${escapeHtml(description)} · Exported ${exportedAt} · ${visNodes.length} nodes · ${visEdges.length} edges</p>`,
        '</header>',
        '<div id="graph"></div>',
        '<div class="legend">',
        '  <div><span class="solid"></span> extracted (user-asserted)</div>',
        '  <div><span class="dashed"></span> inferred (semantic)</div>',
        '  <div><span class="dotted"></span> ambiguous (review)</div>',
        '</div>',
        `<script${nonceAttr}>`,
        `  const DATA = ${payload};`,
        '  const options = {',
        '    nodes: { shape: "dot", size: 14, font: { color: "#e2e8f0", size: 12 }, borderWidth: 1 },',
        '    edges: { arrows: { to: { enabled: true, scaleFactor: 0.5 } }, smooth: false, width: 1 },',
        '    physics: { stabilization: { iterations: 200 }, barnesHut: { gravitationalConstant: -3000, springLength: 100 } },',
        '    interaction: { hover: true, tooltipDelay: 150 },',
        '    groups: {',
        '      decision:        { color: { background: "#805AD5", border: "#553C9A" } },',
        '      architecture:    { color: { background: "#3182CE", border: "#2B6CB0" } },',
        '      convention:      { color: { background: "#38A169", border: "#2F855A" } },',
        '      bug_pattern:     { color: { background: "#E53E3E", border: "#C53030" } },',
        '      troubleshooting: { color: { background: "#DD6B20", border: "#C05621" } },',
        '      note:            { color: { background: "#718096", border: "#4A5568" } },',
        // re-audit 2026-06-25 (product-sanity) — domain-specific node-type colors
        // (Person/Place/PersonalEvent/Memory/Contract) don't belong in Lore Core
        // (schema-agnostic engine; those are application vocabulary). Removed —
        // any unrecognized node type falls through to `default`.
        '      default:         { color: { background: "#4A5568", border: "#2D3748" } },',
        '    }',
        '  };',
        '  const network = new vis.Network(document.getElementById("graph"), DATA, options);',
        '</script>',
        '</body>',
        '</html>',
    ].join('\n');
}

function escapeHtml(s: string): string {
    return s.replace(/[&<>"']/g, (c) => {
        switch (c) {
            case '&': return '&amp;';
            case '<': return '&lt;';
            case '>': return '&gt;';
            case '"': return '&quot;';
            case "'": return '&#39;';
            default: return c;
        }
    });
}
